### ISSUE TITLE
incompatibilities between dependencies

### ISSUE THREAD

**Issue by CarolinaRoyo** [enormandeau/snplift#1]
Following the installation documentation, I have found several conflicts among the dependencies.
Please, could you indicate which version of each dependency is required to avoid all the incompatibilities?
Do you have any suggestions to solve these problems? 
Many thanks

My steps were:

1) create an environment installing dependencies via conda:

conda create -n snplift -c bioconda scipy bwa samtools=1.17

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ncurses conflicts for:
samtools=1.17 -> ncurses[version='>=6.3,<7.0a0']
scipy -> pypy3.9[version='>=7.3.11'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<7.0.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0.0a0|>=6.3,<7.0a0|>=6.4,<7.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']

Package zlib conflicts for:
samtools=1.17 -> zlib[version='>=1.2.13,<1.3.0a0']
bwa -> zlib[version='1.2.11.*|>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0|1.2.8.*']
scipy -> pypy3.9[version='>=7.3.11'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0|>=1.2.12,<1.3.0a0|1.2.8|1.2.11.*']

Package libgfortran conflicts for:
scipy -> libgcc -> libgfortran==3.0.1
scipy -> libgfortran[version='4.*|5.*|>=4.0.0,<5.0.0.a0|>=3.0.1,<4.0.0.a0|>=3.0,<4.0.0.a0']

Package isl conflicts for:
scipy -> libgcc -> isl
bwa -> libgcc -> isl
Note that strict channel priority may have removed packages required for satisfiability.

2) create en environment via conda and  the next environment.ymal file:

name: snplift
channels:
    - defaults
dependencies:
    - python>=3.5
    - scipy
    - bwa
    - samtools>=1.10
environment.yml (END)

conda env create --name snplift -f environment.yml
[...]
Found conflicts! Looking for incompatible packages.
[...]
Package ncurses conflicts for:
python[version='>=3.5'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0|>=6.4,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0.0a0|>=6.1,<7.0.0a0']
python[version='>=3.5'] -> readline[version='>=7.0,<8.0a0'] -> ncurses[version='5.9|5.9.*|6.0.*']

Package python conflicts for:
scipy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']
python[version='>=3.5']
scipy -> pooch -> python[version='3.10.*|3.9.*|>=3.5|>=3.6|>=3.7|3.11.*|3.8.*|3.7.*']

Package libcxx conflicts for:
scipy -> numpy[version='>=1.19.5,<1.27.0'] -> libcxx[version='>=12.0.1']
samtools[version='>=1.10'] -> ncurses[version='>=6.2,<6.3.0a0'] -> libcxx[version='>=10.0.0|>=4.0.1|>=9.0.1']
python[version='>=3.5'] -> libcxx[version='>=10.0.0|>=12.0.0|>=14.0.6|>=4.0.1|>=11.0.1|>=11.0.0|>=10.0.1|>=11.1.0|>=9.0.1|>=9.0.0']
scipy -> libcxx[version='>=10.0.0|>=12.0.0|>=14.0.6|>=4.0.1|>=15.0.7|>=14.0.4|>=13.0.1|>=11.1.0|>=11.0.1|>=11.0.0|>=10.0.1|>=9.0.1|>=9.0.0']

Package libzlib conflicts for:
scipy -> python[version='>=3.11,<3.12.0a0'] -> libzlib[version='>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0|>=1.2.12,<1.3.0a0']
python[version='>=3.5'] -> libzlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']
bwa -> libzlib[version='>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0']
samtools[version='>=1.10'] -> zlib -> libzlib[version='1.2.11|1.2.11|1.2.11|1.2.12|1.2.12|1.2.12|1.2.12|1.2.12|1.2.13',build='h6c3fc93_1014|h6c3fc93_0|hfd90126_4|hfd90126_4|h8a1eda9_5|hfd90126_3|hfe4f2af_2|hfe4f2af_1|h9173be1_1013|h9173be1_1012']
bwa -> zlib -> libzlib[version='1.2.11|1.2.11|1.2.11|1.2.12|1.2.12|1.2.12|1.2.12|1.2.12|1.2.13',build='h6c3fc93_1014|h6c3fc93_0|hfd90126_4|hfd90126_4|h8a1eda9_5|hfd90126_3|hfe4f2af_2|hfe4f2af_1|h9173be1_1013|h9173be1_1012']
python[version='>=3.5'] -> zlib[version='>=1.2.13,<1.3.0a0'] -> libzlib[version='1.2.11|1.2.11|1.2.11|1.2.12|1.2.12|1.2.12|1.2.12|1.2.12|1.2.13',build='h6c3fc93_1014|h6c3fc93_0|hfd90126_4|hfd90126_4|h8a1eda9_5|hfd90126_3|hfe4f2af_2|hfe4f2af_1|h9173be1_1013|h9173be1_1012']
samtools[version='>=1.10'] -> libzlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']

Package mpc conflicts for:
scipy -> libgcc -> mpc[version='>=0.8.0']
bwa -> libgcc -> mpc[version='>=0.8.0']

Package libgfortran conflicts for:
scipy -> libgcc -> libgfortran==3.0.1
scipy -> libgfortran[version='4.*|5.*|>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0|>=3.0,<4.0.0.a0']

Package zlib conflicts for:
python[version='>=3.5'] -> sqlite[version='>=3.41.2,<4.0a0'] -> zlib[version='>=1.2.13,<2.0a0']
python[version='>=3.5'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0|1.2.8']

Package gdbm conflicts for:
scipy -> pypy3.9[version='>=7.3.11'] -> gdbm[version='>=1.18,<1.19.0a0']
python[version='>=3.5'] -> pypy3.9=7.3.11 -> gdbm[version='>=1.18,<1.19.0a0']
bwa -> perl -> gdbm[version='>=1.18|>=1.18,<1.19.0a0']
Note that strict channel priority may have removed packages required for satisfiability.

**Comment by enormandeau** [comment]
This is a conda-specific problem.

I suggest you try to install all the dependencies without any requirement about the minimal version numbers, who are based on the versions I had installed. I think it would probably work. You may have to modify the `00_validate_project.sh` script to permit older versions if needed.

Tell me how it goes.

**Comment by CarolinaRoyo** [comment]
Many thanks.
I modified the versions in the script and it is working.
