### ISSUE TITLE
Convert coordinates between human genomes

### ISSUE THREAD

**Issue by bsb2014** [enormandeau/snplift#2]
Thanks for you developing this kind of tool that is really useful.

I assembled several human genomes, mapped their short reads to their de novo assemblies, and called the SNPs. Because the references are different, I would like to convert snp coordinates on the same reference gh38. Is it possible to use the snplift for that?

Thanks

**Comment by enormandeau** [comment]
Absolutely. This is the use case SNPLift was developed for. You will have to do one SNPLift run per dataset.
