### ISSUE TITLE
SNPlift does not run

### ISSUE THREAD

**Issue by DuttaAnik** [enormandeau/snplift#4]
Hello,
Thank you very much for developing this tool. I am very much looking forward to using it since I have lots of old VCF files. I cloned to the repository and installed all the dependencies. Then, I ran the `run_test.sh` as you recommended. It ran perfectly and produced all the output files. Then, I removed all these downloaded files of the test data and copied my `old_genome.fasta`, `new_genome.fasta` and `old.vcf` to folders `03_genomes` and `04_input_vcf`, respectively. Then, I ran `time ./02_infos/snplift_config.sh`. 

I did not get any output, the command just printed the time and nothing else. No error message or anything.

I did not change anything in the config file as I just renamed my files according to the pattern mentioned in the config file. I also changed the chromosome names in the VCF file to match with the `old_genome.fasta` file.

Could you please suggest what might have gone wrong? Because everything ran smoothly with the `run_test.sh` file.

**Comment by enormandeau** [comment]
Hi. Would it be possible for you to share the full `snplift` folder, including all your data, exactly as you ran in, including the exact command and output you get on the terminal so I can look at this?

**Comment by DuttaAnik** [comment]
Hello,
Thank you for the reply. I have uploaded the entire folder to Google Drive. Please download it from here [https://drive.google.com/file/d/11Spsa3M8mbhgsiyrv-55-47Nnspieerf/view?usp=sharing] to check. I used the following commands and got the time printed on the terminal:
```
time ./02_infos/snplift_config.sh 
./02_infos/snplift_config.sh  0.00s user 0.00s system 69% cpu 0.005 total
```
There was no output except that above line.

**Comment by enormandeau** [comment]
From your command above, you didn't launch SNPLift.

Try:
```
time ./snplift ./02_infos/snplift_config.sh
```

Also, consider deleting your info from Google Drive since the link you shared will be working for everyone.

Take care
