### ISSUE TITLE
Orientation of SNPs

### ISSUE THREAD

**Issue by DuttaAnik** [enormandeau/snplift#6]
Hello,
Thanks again for developing this super useful tool. Along with lifting new SNP positions, would it be possible to add a function to check or update the SNP orientation as well? This will help a lot. Thanks.

**Comment by enormandeau** [comment]
Could you describe exactly what you mean by updating SNP orientation?

**Comment by DuttaAnik** [comment]
Hi, so I meant that SNP can be reported in the context of forward or reverse strand based on which strand (forward or reverse) is used as the reference. For example, a C/G SNP on the forward strand is a G/C SNP on the reverse strand due to complementary base pairing. So, I was wondering if the SNPlift tool can provide such strand information after lifting the SNPs.

**Comment by enormandeau** [comment]
In the config file, by default you have:

`export CORRECT_ALLELES=1    # Reverse complement alleles when new genome region is inverted [0, 1].`

I think that should do what you want.
